name: SonarQube

on:
  push:
    branches:
      - 'main'
      - "release/*"
      - "hotfix/*"
      - "feature/*"
      - "bugfix/*"
      - "test*"
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:11-jdk
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout source code to docker ubuntu container
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_GH_TOKEN }}
          fetch-depth: 0
      - name: Build project
        run: ./gradlew build -x test

#      - name: Cache SonarQube packages
#        uses: actions/cache@v4
#        with:
#          path: ~/.sonar/cache
#          key: ${{ runner.os }}-sonar
#          restore-keys: ${{ runner.os }}-sonar
#      - name: Sonarqube scanning step
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#        run: ./gradlew build sonar --info